# Generated by Django 6.0.4 on 2026-06-16 06:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _migrate_agents_to_suppliers(apps, schema_editor):
    Agent = apps.get_model('apps', 'Agent')
    AgentOrder = apps.get_model('apps', 'AgentOrder')
    for agent in Agent.objects.all():
        if agent.supplier_id:
            supplier = agent.supplier
            changed = []
            if not supplier.agent_name:
                supplier.agent_name = agent.name
                changed.append('agent_name')
            if not supplier.agent_phone and agent.phone:
                supplier.agent_phone = agent.phone
                changed.append('agent_phone')
            if changed:
                supplier.save(update_fields=changed)
        for order in AgentOrder.objects.filter(agent_id=agent.id):
            order.supplier_id = agent.supplier_id
            if not order.agent_name:
                order.agent_name = agent.name
            order.save(update_fields=['supplier_id', 'agent_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_product_size_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentorder',
            options={'ordering': ['-date'], 'verbose_name': 'Agent buyurtmasi', 'verbose_name_plural': 'Agent buyurtmalari'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='creditaccount',
            options={'ordering': ['customer_name'], 'verbose_name': 'Qarz hisobi', 'verbose_name_plural': 'Qarz hisoblari'},
        ),
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Qarz harakati', 'verbose_name_plural': 'Qarz harakatlari'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': "Ombor qoldig'i", 'verbose_name_plural': 'Ombor qoldiqlari'},
        ),
        migrations.AlterModelOptions(
            name='poscartdraft',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Kassa chernovigi', 'verbose_name_plural': 'Kassa chernoviklari'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date'], 'verbose_name': 'Xarid buyurtmasi', 'verbose_name_plural': 'Xarid buyurtmalari'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'verbose_name': 'Buyurtma qatori', 'verbose_name_plural': 'Buyurtma qatorlari'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date', '-external_id'], 'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='saleline',
            options={'verbose_name': 'Sotuv qatori', 'verbose_name_plural': 'Sotuv qatorlari'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Diler', 'verbose_name_plural': 'Dilerlar'},
        ),
        migrations.AlterModelOptions(
            name='suppliercatalogitem',
            options={'ordering': ['name'], 'verbose_name': 'Diler katalog elementi', 'verbose_name_plural': 'Diler katalog elementlari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Ombor', 'verbose_name_plural': 'Omborlar'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='agentorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='agentorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_orders', to='apps.supplier', verbose_name='Diler'),
        ),
        migrations.AddField(
            model_name='agentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='poscartdraft',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Chernovik'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agent ismi'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agent telefoni'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='suppliercatalogitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='suppliercatalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agent ismi'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_orders', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='items',
            field=models.CharField(max_length=500, verbose_name='Mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID identifikator'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Qarz qoldig'i"),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apps.creditaccount', verbose_name='Qarz hisobi'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='kind',
            field=models.CharField(choices=[('charge', 'Qarz (sotuv)'), ('payment', "To'lov")], max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='apps.sale', verbose_name="Bog'langan sotuv"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='apps.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.warehouse', verbose_name='Ombor'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cart_drafts', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cart_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='items',
            field=models.JSONField(default=list, verbose_name='Savat elementlari'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='label',
            field=models.CharField(max_length=120, verbose_name='Navbat nomi'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='pay_method',
            field=models.CharField(default='Naqd', max_length=50, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami'),
        ),
        migrations.AlterField(
            model_name='poscartdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Shtrix-kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='apps.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, default='📦', max_length=16, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name="Hajm/og'irlik"),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy qoldiq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='dona', max_length=20, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(verbose_name='Buyurtma sanasi'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='external_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qabul qilingan sana'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Yetkazilyapti', 'Yetkazilyapti'), ('Yetkazilgan', 'Yetkazilgan')], default='Kutilmoqda', max_length=50, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.supplier', verbose_name='Diler'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diler nomi (nusxa)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='apps.suppliercatalogitem', verbose_name='Katalog elementi'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apps.purchaseorder', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hajm'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name="O'lchov"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kassir ismi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='external_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Chek raqami'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='items',
            field=models.JSONField(default=list, verbose_name='Savat (JSON)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(default='Naqd', max_length=50, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apps.sale', verbose_name='Sotuv'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Diler nomi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Diler telefoni'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('Faol', 'Faol'), ('Nofaol', 'Nofaol')], default='Faol', max_length=50, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami buyurtmalar'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shtrix-kod'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='default_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kirim narxi'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_catalog_items', to='apps.product', verbose_name="Bog'langan mahsulot"),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hajm'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='apps.supplier', verbose_name='Diler'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='unit',
            field=models.CharField(blank=True, default='ta', max_length=20, verbose_name="O'lchov"),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID identifikator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin panelga kirish'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('boss', 'Boss'), ('owner', 'Egasi'), ('manager', 'Menejer'), ('cashier', 'Kassir')], default='cashier', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ombor nomi'),
        ),
        migrations.RunPython(_migrate_agents_to_suppliers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='agentorder',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
