# Generated by Django 6.0.4 on 2026-06-16 06:43

from django.db import migrations


def merge_customers_into_credit(apps, schema_editor):
    """Eski Customer yozuvlarini CreditAccount (qarzdor mijoz) ga ko'chirish."""
    Customer = apps.get_model('apps', 'Customer')
    CreditAccount = apps.get_model('apps', 'CreditAccount')
    for customer in Customer.objects.all():
        if customer.phone:
            exists = CreditAccount.objects.filter(branch=customer.branch, phone=customer.phone).exists()
        else:
            exists = CreditAccount.objects.filter(
                branch=customer.branch,
                customer_name__iexact=customer.name,
            ).exists()
        if not exists:
            CreditAccount.objects.create(
                branch=customer.branch,
                customer_name=customer.name,
                phone=customer.phone or '',
                balance=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_refactor_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditaccount',
            options={'ordering': ['customer_name'], 'verbose_name': 'Qarzdor mijoz', 'verbose_name_plural': 'Qarzdor mijozlar'},
        ),
        migrations.RunPython(merge_customers_into_credit, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
