# Generated by Django 6.0.4 on 2026-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_sale_payment_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentorder',
            name='agent_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agent ismi'),
        ),
        migrations.AlterField(
            model_name='agentorder',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='note',
            field=models.CharField(blank=True, max_length=20, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='Shtrix-kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Diler nomi (nusxa)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kassir ismi'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='agent_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agent ismi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Diler nomi'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ombor nomi'),
        ),
    ]
